---
title: "density_dependence_analysis"
author: "Abby Robinson"
date: "4/5/2023"
output: html_document
---

Install the "Curl" Package and then load the package library using the code below 

```{r}
library(curl)
```

Use the "curl" command to load the data into R using the data file link from the repo 

```{r}
c <- curl("https://raw.githubusercontent.com/butterfliesrcool/Density_Dependent_Dynamics/main/density_dependence_count_yes_maybe.csv")
ym_count <- read.csv(c, header = TRUE, sep = ",")
head(ym_count)
```

```{r}
# summarizing attacks 
aggregate(x= ym_count$attacks, by= list(ym_count$species, ym_count$experiment, ym_count$week), FUN=sum)
```

```{r}
p <- curl("https://raw.githubusercontent.com/butterfliesrcool/Density_Dependent_Dynamics/main/density_dependence_count_yes.csv")
y_count <- read.csv(p, header = TRUE, sep = ",")
head(y_count)
```

```{r}
# summarizing attacks 
aggregate(x= y_count$attacks, by= list(y_count$species, y_count$experiment, y_count$week), FUN=sum)
```

```{r}
b <- curl("https://raw.githubusercontent.com/butterfliesrcool/Density_Dependent_Dynamics/main/density_dependence_binomial.csv")
binomial <- read.csv(b, header = TRUE, sep = ",", na.strings=c("","NA"))
binomial[is.na(binomial)] <- "N" 
head(binomial)
```

```{r}
# summarizing attacks 
aggregate(x= binomial$attacks, by= list(binomial$species, binomial$experiment, binomial$week), FUN=sum)
```
```{r}
yes <- subset(binomial, confidence %in% c("Y", "N"))
LD <- subset(yes, experiment == "low_density")
```
```{r}
library(survival)
library(survminer)
coxph(Surv(experiment_day, attacks) ~ species, data = LD)
```

```{r}
### non-ggplot plot (lots of easy resources online to make these pretty

survival <- survfit(Surv(experiment_day, attacks) ~ species, data = LD)
plot(survival,     
    xlab = "days", 
    ylab = "facsimile Survival", 
    yaxis = c(0.8, 1.0)
    )

segments(35, .372, 40, .372, col = c("darkolivegreen"), lwd=3)
segments(35, .104, 40, .104, col = c("darkorchid4"), lwd=3)
```


